# Generated by Django 4.0.4 on 2022-05-01 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_result_max_score_remove_result_min_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.quiz')),
            ],
        ),
    ]
