# Generated by Django 4.0.4 on 2022-05-01 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_userresult_test_result_alter_userresult_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizes'},
        ),
    ]
