# Generated by Django 4.0.4 on 2022-05-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_alter_useradditionalresult_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userresult',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='userresult',
            constraint=models.UniqueConstraint(fields=('user', 'quiz'), name='unique_quiz_user'),
        ),
    ]
