# Generated by Django 4.0.4 on 2022-05-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_alter_userresult_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userresult',
            name='unique_quiz_user',
        ),
        migrations.AddConstraint(
            model_name='userresult',
            constraint=models.UniqueConstraint(fields=('test_result', 'quiz'), name='unique_quiz_user'),
        ),
    ]
