# Generated by Django 4.0.4 on 2022-05-04 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_alter_userresult_test_result'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userresult',
            name='unique_quiz_user',
        ),
    ]
